"""add import batch tables

Revision ID: 140dff47a9a2
Revises: 51018d005651
Create Date: 2026-02-06 14:43:09.199844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '140dff47a9a2'
down_revision: Union[str, Sequence[str], None] = '51018d005651'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('mapping_json', sa.Text(), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('success_rows', sa.Integer(), nullable=False),
    sa.Column('error_rows', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_batch_id'), 'import_batch', ['id'], unique=False)
    op.create_table('import_error',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=True),
    sa.Column('field', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batch.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_error_id'), 'import_error', ['id'], unique=False)
    op.create_table('import_raw_row',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('raw_json', sa.Text(), nullable=False),
    sa.Column('normalized_hint', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batch.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_raw_row_id'), 'import_raw_row', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_import_raw_row_id'), table_name='import_raw_row')
    op.drop_table('import_raw_row')
    op.drop_index(op.f('ix_import_error_id'), table_name='import_error')
    op.drop_table('import_error')
    op.drop_index(op.f('ix_import_batch_id'), table_name='import_batch')
    op.drop_table('import_batch')
    # ### end Alembic commands ###
