"""add hourly_rate to resources

Revision ID: 16518fa67fcb
Revises: 51018d005651
Create Date: 2026-02-10 10:56:23.808455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16518fa67fcb'
down_revision: Union[str, Sequence[str], None] = '51018d005651'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('resources', sa.Column('hourly_rate', sa.Numeric(precision=12, scale=2), nullable=True))

    op.add_column(
        'resources',
        sa.Column('currency', sa.String(length=10), nullable=False, server_default='TRY')
    )

    op.alter_column('resources', 'currency', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_time_entries_source_external_id'), 'time_entries', ['source', 'external_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('resources', 'currency')
    op.drop_column('resources', 'hourly_rate')
    # ### end Alembic commands ###
