"""add import_error and raw_row_status

Revision ID: 28d40d4ed96d
Revises: 140dff47a9a2
Create Date: 2026-02-07 11:18:00.285524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28d40d4ed96d'
down_revision: Union[str, Sequence[str], None] = '140dff47a9a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_error', sa.Column('raw_row_id', sa.Integer(), nullable=True))
    op.add_column('import_error', sa.Column('severity', sa.String(length=10), nullable=False))
    op.add_column('import_error', sa.Column('error_code', sa.String(length=50), nullable=False))
    op.add_column('import_error', sa.Column('field_name', sa.String(length=100), nullable=True))
    op.add_column('import_error', sa.Column('raw_value', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'import_error', 'import_raw_row', ['raw_row_id'], ['id'], ondelete='CASCADE')
    op.drop_column('import_error', 'field')
    op.drop_column('import_error', 'raw_json')
    op.drop_column('import_error', 'row_number')
    op.add_column(
    'import_raw_row',
    sa.Column('row_status', sa.String(length=10), nullable=False, server_default='PENDING')
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('import_raw_row', 'row_status')
    op.add_column('import_error', sa.Column('row_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('import_error', sa.Column('raw_json', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('import_error', sa.Column('field', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'import_error', type_='foreignkey')
    op.drop_column('import_error', 'raw_value')
    op.drop_column('import_error', 'field_name')
    op.drop_column('import_error', 'error_code')
    op.drop_column('import_error', 'severity')
    op.drop_column('import_error', 'raw_row_id')
    # ### end Alembic commands ###
